# Generated by Django 5.1.3 on 2024-11-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0002_alter_roommember_id_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
